# Generated by Django 5.1.4 on 2025-03-21 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hyperstat',
            name='stat_increase',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hyperstat',
            name='stat_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hyperstat',
            name='stat_point',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
