# Generated by Django 5.1.4 on 2025-03-23 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='face',
            name='face_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hair',
            name='hair_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='skin',
            name='skin_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
