# Generated by Django 5.1.4 on 2025-03-27 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hexastatcore',
            name='main_stat_level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hexastatcore',
            name='main_stat_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hexastatcore',
            name='stat_grade',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hexastatcore',
            name='sub_stat_level_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hexastatcore',
            name='sub_stat_level_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hexastatcore',
            name='sub_stat_name_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hexastatcore',
            name='sub_stat_name_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
