# Generated by Django 5.0.7 on 2024-07-16 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterPopularity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(help_text='조회 기준일 (KST, 일 단위 데이터로 시, 분은 일괄 0으로 표기)')),
                ('popularity', models.BigIntegerField(help_text='캐릭터 인기도')),
                ('character', models.ForeignKey(help_text='캐릭터 기본 정보', on_delete=django.db.models.deletion.CASCADE, related_name='popularity', to='characters.characterbasic')),
            ],
            options={
                'verbose_name': 'Character Popularity',
                'verbose_name_plural': 'Character Popularities',
            },
        ),
    ]
