# Generated by Django 5.1.4 on 2025-03-20 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterid',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
