# Generated by Django 5.1.4 on 2025-03-27 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_alter_hexastatcore_main_stat_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petequipment',
            name='pet_icon',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='petequipment',
            name='pet_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='petequipment',
            name='pet_nickname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
