# Generated by Django 5.0.7 on 2024-07-16 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_characterpopularity'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, help_text='조회 기준일', null=True)),
                ('character_class', models.CharField(help_text='캐릭터 직업', max_length=255)),
                ('remain_ap', models.IntegerField(default=0, help_text='남은 AP')),
            ],
        ),
        migrations.CreateModel(
            name='StatDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_name', models.CharField(help_text='스탯 이름', max_length=255)),
                ('stat_value', models.CharField(help_text='스탯 값', max_length=255)),
                ('character_stat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_stat', to='characters.characterstat')),
            ],
        ),
    ]
