# Generated by Django 5.1.4 on 2025-03-23 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_alter_face_face_name_alter_hair_hair_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashitemequipment',
            name='android_item_gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
