# Generated by Django 5.1.4 on 2024-12-22 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_alter_characteritemequipment_item_base_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characteritemequipment',
            name='item_etc_option',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='characters.itemetcoption'),
        ),
        migrations.AlterField(
            model_name='characteritemequipment',
            name='item_starforce_option',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='characters.itemstarforceoption'),
        ),
        migrations.AlterField(
            model_name='characteritemequipment',
            name='item_total_option',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='characters.itemtotaloption'),
        ),
    ]
