# Generated by Django 5.1.4 on 2025-03-21 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_alter_hyperstat_stat_increase_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='title_shape_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='title',
            name='title_shape_icon',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='title',
            name='title_shape_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
