# Generated by Django 5.1.4 on 2025-03-21 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0003_title_title_shape_description_title_title_shape_icon_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemequipment',
            old_name='scroll_upgradable_count',
            new_name='scroll_upgradeable_count',
        ),
    ]
