# Generated by Django 5.1.4 on 2025-03-27 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0003_alter_petequipment_pet_icon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charactercashitemequipment',
            name='character_look_mode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
