# Generated by Django 5.1.4 on 2024-12-22 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0003_alter_characteritemequipment_item_etc_option_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='characteritemequipment',
            name='additional_potential_option_1',
        ),
        migrations.RemoveField(
            model_name='characteritemequipment',
            name='additional_potential_option_2',
        ),
        migrations.RemoveField(
            model_name='characteritemequipment',
            name='additional_potential_option_3',
        ),
        migrations.RemoveField(
            model_name='characteritemequipment',
            name='additional_potential_option_flag',
        ),
        migrations.RemoveField(
            model_name='characteritemequipment',
            name='additional_potential_option_grade',
        ),
        migrations.RemoveField(
            model_name='characteritemequipment',
            name='cuttable_count',
        ),
        migrations.RemoveField(
            model_name='characteritemequipment',
            name='date_expire',
        ),
        migrations.RemoveField(
            model_name='characteritemequipment',
            name='equipment_level_increase',
        ),
        migrations.RemoveField(
            model_name='characteritemequipment',
            name='golden_hammer_flag',
        ),
        migrations.RemoveField(
            model_name='characteritemequipment',
            name='growth_exp',
        ),
        migrations.RemoveField(
            model_name='characteritemequipment',
            name='growth_level',
        ),
        migrations.RemoveField(
            model_name='characteritemequipment',
            name='is_dragon_equipment',
        ),
        migrations.RemoveField(
            model_name='characteritemequipment',
            name='is_mechanic_equipment',
        ),
        migrations.RemoveField(
            model_name='characteritemequipment',
            name='item_add_option',
        ),
        migrations.RemoveField(
            model_name='characteritemequipment',
            name='item_base_option',
        ),
        migrations.RemoveField(
            model_name='characteritemequipment',
            name='item_description',
        ),
        migrations.RemoveField(
            model_name='characteritemequipment',
            name='item_equipment_part',
        ),
        migrations.RemoveField(
            model_name='characteritemequipment',
            name='item_equipment_slot',
        ),
        migrations.RemoveField(
            model_name='characteritemequipment',
            name='item_etc_option',
        ),
        migrations.RemoveField(
            model_name='characteritemequipment',
            name='item_exceptional_option',
        ),
        migrations.RemoveField(
            model_name='characteritemequipment',
            name='item_gender',
        ),
        migrations.RemoveField(
            model_name='characteritemequipment',
            name='item_icon',
        ),
        migrations.RemoveField(
            model_name='characteritemequipment',
            name='item_name',
        ),
        migrations.RemoveField(
            model_name='characteritemequipment',
            name='item_shape_icon',
        ),
        migrations.RemoveField(
            model_name='characteritemequipment',
            name='item_shape_name',
        ),
        migrations.RemoveField(
            model_name='characteritemequipment',
            name='item_starforce_option',
        ),
        migrations.RemoveField(
            model_name='characteritemequipment',
            name='item_total_option',
        ),
        migrations.RemoveField(
            model_name='characteritemequipment',
            name='potential_option_1',
        ),
        migrations.RemoveField(
            model_name='characteritemequipment',
            name='potential_option_2',
        ),
        migrations.RemoveField(
            model_name='characteritemequipment',
            name='potential_option_3',
        ),
        migrations.RemoveField(
            model_name='characteritemequipment',
            name='potential_option_flag',
        ),
        migrations.RemoveField(
            model_name='characteritemequipment',
            name='potential_option_grade',
        ),
        migrations.RemoveField(
            model_name='characteritemequipment',
            name='scroll_resilience_count',
        ),
        migrations.RemoveField(
            model_name='characteritemequipment',
            name='scroll_upgradable_count',
        ),
        migrations.RemoveField(
            model_name='characteritemequipment',
            name='scroll_upgrade',
        ),
        migrations.RemoveField(
            model_name='characteritemequipment',
            name='soul_name',
        ),
        migrations.RemoveField(
            model_name='characteritemequipment',
            name='soul_option',
        ),
        migrations.RemoveField(
            model_name='characteritemequipment',
            name='special_ring_level',
        ),
        migrations.RemoveField(
            model_name='characteritemequipment',
            name='starforce',
        ),
        migrations.RemoveField(
            model_name='characteritemequipment',
            name='starforce_scroll_flag',
        ),
        migrations.AlterField(
            model_name='characteritemequipment',
            name='title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='characters.title'),
        ),
        migrations.CreateModel(
            name='ItemEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_equipment_part', models.CharField(max_length=50)),
                ('item_equipment_slot', models.CharField(max_length=50)),
                ('item_name', models.CharField(max_length=255)),
                ('item_icon', models.URLField()),
                ('item_description', models.TextField(blank=True, null=True)),
                ('item_shape_name', models.CharField(blank=True, max_length=255, null=True)),
                ('item_shape_icon', models.URLField(blank=True, null=True)),
                ('item_gender', models.CharField(blank=True, max_length=10, null=True)),
                ('potential_option_flag', models.CharField(max_length=10)),
                ('additional_potential_option_flag', models.CharField(max_length=10)),
                ('potential_option_grade', models.CharField(blank=True, max_length=50, null=True)),
                ('additional_potential_option_grade', models.CharField(blank=True, max_length=50, null=True)),
                ('potential_option_1', models.CharField(blank=True, max_length=255, null=True)),
                ('potential_option_2', models.CharField(blank=True, max_length=255, null=True)),
                ('potential_option_3', models.CharField(blank=True, max_length=255, null=True)),
                ('additional_potential_option_1', models.CharField(blank=True, max_length=255, null=True)),
                ('additional_potential_option_2', models.CharField(blank=True, max_length=255, null=True)),
                ('additional_potential_option_3', models.CharField(blank=True, max_length=255, null=True)),
                ('equipment_level_increase', models.IntegerField(blank=True, null=True)),
                ('growth_exp', models.IntegerField(blank=True, null=True)),
                ('growth_level', models.IntegerField(blank=True, null=True)),
                ('scroll_upgrade', models.CharField(max_length=10)),
                ('cuttable_count', models.CharField(max_length=10)),
                ('golden_hammer_flag', models.CharField(max_length=10)),
                ('scroll_resilience_count', models.CharField(max_length=10)),
                ('scroll_upgradable_count', models.CharField(blank=True, max_length=10, null=True)),
                ('soul_name', models.CharField(blank=True, max_length=255, null=True)),
                ('soul_option', models.CharField(blank=True, max_length=255, null=True)),
                ('starforce', models.CharField(max_length=10)),
                ('starforce_scroll_flag', models.CharField(max_length=10)),
                ('special_ring_level', models.IntegerField(blank=True, null=True)),
                ('date_expire', models.DateTimeField(blank=True, null=True)),
                ('item_add_option', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='characters.itemaddoption')),
                ('item_base_option', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='characters.itembaseoption')),
                ('item_etc_option', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='characters.itemetcoption')),
                ('item_exceptional_option', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='characters.itemexceptionaloption')),
                ('item_starforce_option', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='characters.itemstarforceoption')),
                ('item_total_option', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='characters.itemtotaloption')),
            ],
        ),
        migrations.AddField(
            model_name='characteritemequipment',
            name='dragon_equipment',
            field=models.ManyToManyField(blank=True, related_name='character_dragon_equipment', to='characters.itemequipment'),
        ),
        migrations.AddField(
            model_name='characteritemequipment',
            name='item_equipment',
            field=models.ManyToManyField(related_name='character_equipments', to='characters.itemequipment'),
        ),
        migrations.AddField(
            model_name='characteritemequipment',
            name='item_equipment_preset_1',
            field=models.ManyToManyField(related_name='character_preset_1', to='characters.itemequipment'),
        ),
        migrations.AddField(
            model_name='characteritemequipment',
            name='item_equipment_preset_2',
            field=models.ManyToManyField(related_name='character_preset_2', to='characters.itemequipment'),
        ),
        migrations.AddField(
            model_name='characteritemequipment',
            name='item_equipment_preset_3',
            field=models.ManyToManyField(related_name='character_preset_3', to='characters.itemequipment'),
        ),
        migrations.AddField(
            model_name='characteritemequipment',
            name='mechanic_equipment',
            field=models.ManyToManyField(blank=True, related_name='character_mechanic_equipment', to='characters.itemequipment'),
        ),
    ]
