# Generated by Django 5.1.4 on 2025-03-24 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0003_cashitemequipment_android_item_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='characterlinkskill',
            name='character_link_skill',
        ),
        migrations.RemoveField(
            model_name='characterlinkskill',
            name='character_owned_link_skill',
        ),
        migrations.AddField(
            model_name='characterlinkskill',
            name='character_link_skill',
            field=models.ManyToManyField(blank=True, related_name='main_link', to='characters.linkskill'),
        ),
        migrations.AddField(
            model_name='characterlinkskill',
            name='character_owned_link_skill',
            field=models.ManyToManyField(blank=True, related_name='owned_link', to='characters.linkskill'),
        ),
    ]
