# Generated by Django 5.0.7 on 2024-07-16 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0003_characterstat_statdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterstat',
            name='character',
            field=models.ForeignKey(default='', help_text='캐릭터 기본 정보', on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='characters.characterbasic'),
            preserve_default=False,
        ),
    ]
