# Generated by Django 5.0.7 on 2024-07-16 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0004_characterstat_character'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterbasic',
            name='character_date_create',
            field=models.DateTimeField(blank=True, help_text='캐릭터 생성일 (KST)', null=True),
        ),
    ]
