# Generated by Django 5.1.4 on 2024-12-22 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0004_remove_characteritemequipment_additional_potential_option_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemequipment',
            name='additional_potential_option_flag',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='itemequipment',
            name='potential_option_flag',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
