# Generated by Django 5.1.4 on 2025-03-24 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0004_remove_characterlinkskill_character_link_skill_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='characterlinkskill',
            name='character_owned_link_skill',
        ),
        migrations.AddField(
            model_name='characterlinkskill',
            name='character_owned_link_skill',
            field=models.OneToOneField(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='owned_link', to='characters.linkskill'),
            preserve_default=False,
        ),
    ]
