# Generated by Django 5.1.4 on 2025-03-21 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0005_alter_itemequipment_cuttable_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkskill',
            name='skill_effect_next',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='linkskill',
            name='skill_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='linkskill',
            name='skill_effect',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='linkskill',
            name='skill_icon',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='linkskill',
            name='skill_level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='linkskill',
            name='skill_name',
            field=models.CharField(max_length=100),
        ),
    ]
