# Generated by Django 5.1.4 on 2025-03-13 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0005_alter_itemequipment_additional_potential_option_flag_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterSymbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('symbol_name', models.CharField(max_length=255)),
                ('symbol_icon', models.URLField()),
                ('symbol_description', models.TextField()),
                ('symbol_force', models.CharField(max_length=50)),
                ('symbol_level', models.IntegerField()),
                ('symbol_exp', models.IntegerField()),
                ('symbol_exp_required', models.IntegerField()),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_symbols', to='characters.characterbasic')),
            ],
        ),
    ]
