# Generated by Django 5.0.7 on 2024-07-16 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0005_alter_characterbasic_character_date_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterpopularity',
            name='date',
            field=models.DateTimeField(blank=True, help_text='조회 기준일 (KST, 일 단위 데이터로 시, 분은 일괄 0으로 표기)', null=True),
        ),
    ]
