# Generated by Django 5.1.4 on 2025-03-25 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0006_alter_characterlinkskill_character_owned_link_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='skill_effect',
            field=models.TextField(blank=True, null=True),
        ),
    ]
