# Generated by Django 5.1.4 on 2025-03-13 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0006_charactersymbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashitemequipment',
            name='cash_item_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
