# Generated by Django 5.1.4 on 2025-03-27 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0006_alter_characterhexamatrixstat_character_hexa_stat_core_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='androidequipmentpreset',
            name='android_icon',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='androidequipmentpreset',
            name='android_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='androidequipmentpreset',
            name='android_nickname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
