# Generated by Django 5.1.4 on 2025-03-21 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0006_linkskill_skill_effect_next_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charactervmatrix',
            name='preset_no',
        ),
    ]
