# Generated by Django 5.1.4 on 2025-03-13 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0007_alter_cashitemequipment_cash_item_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CharacterSymbol',
        ),
    ]
