# Generated by Django 5.1.4 on 2025-03-21 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0007_remove_charactervmatrix_preset_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vcore',
            name='slot_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vcore',
            name='slot_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vcore',
            name='v_core_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vcore',
            name='v_core_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vcore',
            name='v_core_skill_1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vcore',
            name='v_core_skill_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vcore',
            name='v_core_skill_3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vcore',
            name='v_core_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
