# Generated by Django 5.1.4 on 2025-03-22 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0008_alter_vcore_slot_id_alter_vcore_slot_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterability',
            name='preset_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='charactercashitemequipment',
            name='preset_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='characterhyperstat',
            name='use_preset_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='characteritemequipment',
            name='preset_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='characterlinkskill',
            name='preset_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
