# Generated by Django 5.1.4 on 2025-11-23 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0009_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterbasic',
            name='character_info_url',
            field=models.URLField(blank=True, help_text='캐릭터 정보 페이지 URL (인벤토리 크롤링용)', max_length=500, null=True),
        ),
    ]
