# Generated by Django 5.1.4 on 2025-03-22 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0009_alter_characterability_preset_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterbasichistory',
            name='character_image',
            field=models.TextField(),
        ),
    ]
