# Generated by Django 5.1.4 on 2025-11-23 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0010_characterbasic_character_info_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='detail_url',
            field=models.URLField(blank=True, help_text='아이템 상세 페이지 URL', null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='has_detail',
            field=models.BooleanField(default=False, help_text='상세 정보 크롤링 완료 여부'),
        ),
        migrations.CreateModel(
            name='ItemDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_category', models.CharField(blank=True, help_text='장비 분류 (예: 무기, 방어구)', max_length=100, null=True)),
                ('required_level', models.IntegerField(blank=True, help_text='착용 가능 레벨', null=True)),
                ('required_job', models.CharField(blank=True, help_text='착용 가능 직업', max_length=255, null=True)),
                ('attack_power', models.IntegerField(blank=True, help_text='공격력', null=True)),
                ('magic_power', models.IntegerField(blank=True, help_text='마력', null=True)),
                ('str_stat', models.IntegerField(blank=True, help_text='STR', null=True)),
                ('dex_stat', models.IntegerField(blank=True, help_text='DEX', null=True)),
                ('int_stat', models.IntegerField(blank=True, help_text='INT', null=True)),
                ('luk_stat', models.IntegerField(blank=True, help_text='LUK', null=True)),
                ('hp_stat', models.IntegerField(blank=True, help_text='HP', null=True)),
                ('mp_stat', models.IntegerField(blank=True, help_text='MP', null=True)),
                ('defense', models.IntegerField(blank=True, help_text='방어력', null=True)),
                ('all_stat', models.IntegerField(blank=True, help_text='올스탯', null=True)),
                ('boss_damage', models.IntegerField(blank=True, help_text='보스 공격력 증가 (%)', null=True)),
                ('ignore_defense', models.IntegerField(blank=True, help_text='방어율 무시 (%)', null=True)),
                ('upgrade_count', models.IntegerField(blank=True, help_text='업그레이드 가능 횟수', null=True)),
                ('upgrades_used', models.IntegerField(blank=True, help_text='사용한 업그레이드 횟수', null=True)),
                ('potential_grade', models.CharField(blank=True, help_text='잠재능력 등급 (레어/에픽/유니크/레전드리)', max_length=50, null=True)),
                ('potential_option_1', models.CharField(blank=True, help_text='잠재능력 옵션 1', max_length=255, null=True)),
                ('potential_option_2', models.CharField(blank=True, help_text='잠재능력 옵션 2', max_length=255, null=True)),
                ('potential_option_3', models.CharField(blank=True, help_text='잠재능력 옵션 3', max_length=255, null=True)),
                ('additional_potential_grade', models.CharField(blank=True, help_text='에디셔널 잠재능력 등급', max_length=50, null=True)),
                ('additional_potential_option_1', models.CharField(blank=True, help_text='에디셔널 잠재능력 옵션 1', max_length=255, null=True)),
                ('additional_potential_option_2', models.CharField(blank=True, help_text='에디셔널 잠재능력 옵션 2', max_length=255, null=True)),
                ('additional_potential_option_3', models.CharField(blank=True, help_text='에디셔널 잠재능력 옵션 3', max_length=255, null=True)),
                ('soul_name', models.CharField(blank=True, help_text='소울 이름', max_length=255, null=True)),
                ('soul_option', models.CharField(blank=True, help_text='소울 옵션', max_length=255, null=True)),
                ('crawled_at', models.DateTimeField(auto_now_add=True, help_text='상세 정보 크롤링 시간')),
                ('inventory_item', models.OneToOneField(help_text='연결된 인벤토리 아이템', on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='characters.inventory')),
            ],
            options={
                'ordering': ['-crawled_at'],
                'indexes': [models.Index(fields=['inventory_item'], name='characters__invento_017324_idx'), models.Index(fields=['potential_grade'], name='characters__potenti_eaa226_idx'), models.Index(fields=['additional_potential_grade'], name='characters__additio_795cb0_idx')],
            },
        ),
    ]
