# Generated by Django 5.1.4 on 2025-11-25 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0011_inventory_detail_url_inventory_has_detail_itemdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_type', models.CharField(choices=[('shared', 'Shared Storage'), ('personal', 'Personal Storage')], help_text='창고 유형 (shared/personal)', max_length=10)),
                ('item_name', models.CharField(help_text='아이템 이름', max_length=255)),
                ('item_icon', models.URLField(help_text='아이템 아이콘 URL')),
                ('quantity', models.IntegerField(default=1, help_text='아이템 수량')),
                ('item_options', models.JSONField(blank=True, help_text='아이템 옵션 (강화, 잠재능력 등)', null=True)),
                ('slot_position', models.IntegerField(help_text='창고 슬롯 위치')),
                ('expiry_date', models.DateTimeField(blank=True, help_text='기간제 아이템 만료 날짜', null=True)),
                ('crawled_at', models.DateTimeField(auto_now_add=True, help_text='크롤링된 시간')),
                ('character_basic', models.ForeignKey(help_text='연결된 캐릭터', on_delete=django.db.models.deletion.CASCADE, related_name='storage_items', to='characters.characterbasic')),
            ],
            options={
                'ordering': ['-crawled_at', 'storage_type', 'slot_position'],
                'indexes': [models.Index(fields=['character_basic', 'storage_type'], name='characters__charact_e675cb_idx'), models.Index(fields=['expiry_date'], name='characters__expiry__f62344_idx'), models.Index(fields=['character_basic', '-crawled_at'], name='characters__charact_97bcc1_idx')],
            },
        ),
    ]
