# Generated by Django 5.1.4 on 2025-11-26 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0012_add_storage_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterbasic',
            name='meso',
            field=models.BigIntegerField(blank=True, help_text='캐릭터 보유 메소', null=True),
        ),
        migrations.AddField(
            model_name='storage',
            name='meso',
            field=models.BigIntegerField(blank=True, help_text='창고 메소 (크롤링 시점 기준)', null=True),
        ),
    ]
