# Generated by Django 5.1.4 on 2025-11-26 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0013_characterbasic_meso_storage_meso'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterbasichistory',
            name='meso',
            field=models.BigIntegerField(blank=True, help_text='캐릭터 보유 메소 (AC 2.5.4 히스토리 보관)', null=True),
        ),
    ]
