# Generated by Django 5.1.4 on 2025-12-02 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0014_add_meso_to_characterbasichistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='crawled_at',
            field=models.DateTimeField(help_text='크롤링된 시간'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='crawled_at',
            field=models.DateTimeField(help_text='크롤링된 시간'),
        ),
    ]
