# Generated by Django 5.1.4 on 2025-12-05 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0015_alter_inventory_crawled_at_alter_storage_crawled_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'ordering': ['-crawled_at', 'item_type', 'slot_position']},
        ),
        migrations.AddField(
            model_name='inventory',
            name='item_type',
            field=models.CharField(choices=[('equips', '장비'), ('consumables', '소비'), ('miscs', '기타'), ('installables', '설치'), ('cashes', '캐시')], default='miscs', help_text='아이템 유형 (장비/소비/기타/설치/캐시)', max_length=20),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['character_basic', 'item_type'], name='characters__charact_b2132b_idx'),
        ),
    ]
