# Generated by Django 5.1.4 on 2025-12-25 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0016_alter_inventory_options_inventory_item_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemdetail',
            name='attack_breakdown',
            field=models.JSONField(blank=True, help_text='공격력 분해값 {total, base, bonus, scroll}', null=True),
        ),
        migrations.AddField(
            model_name='itemdetail',
            name='defense_breakdown',
            field=models.JSONField(blank=True, help_text='방어력 분해값 {total, base, bonus, scroll}', null=True),
        ),
        migrations.AddField(
            model_name='itemdetail',
            name='dex_breakdown',
            field=models.JSONField(blank=True, help_text='DEX 분해값 {total, base, bonus, scroll}', null=True),
        ),
        migrations.AddField(
            model_name='itemdetail',
            name='etc_info',
            field=models.JSONField(blank=True, help_text='기타 정보 (교환 불가, 고유장착 등)', null=True),
        ),
        migrations.AddField(
            model_name='itemdetail',
            name='hp_breakdown',
            field=models.JSONField(blank=True, help_text='HP 분해값 {total, base, bonus, scroll}', null=True),
        ),
        migrations.AddField(
            model_name='itemdetail',
            name='int_breakdown',
            field=models.JSONField(blank=True, help_text='INT 분해값 {total, base, bonus, scroll}', null=True),
        ),
        migrations.AddField(
            model_name='itemdetail',
            name='luk_breakdown',
            field=models.JSONField(blank=True, help_text='LUK 분해값 {total, base, bonus, scroll}', null=True),
        ),
        migrations.AddField(
            model_name='itemdetail',
            name='magic_breakdown',
            field=models.JSONField(blank=True, help_text='마력 분해값 {total, base, bonus, scroll}', null=True),
        ),
        migrations.AddField(
            model_name='itemdetail',
            name='max_star_force',
            field=models.IntegerField(blank=True, help_text='최대 스타포스 강화 가능 수치', null=True),
        ),
        migrations.AddField(
            model_name='itemdetail',
            name='mp_breakdown',
            field=models.JSONField(blank=True, help_text='MP 분해값 {total, base, bonus, scroll}', null=True),
        ),
        migrations.AddField(
            model_name='itemdetail',
            name='required_dex',
            field=models.IntegerField(blank=True, help_text='착용 필요 DEX', null=True),
        ),
        migrations.AddField(
            model_name='itemdetail',
            name='required_int',
            field=models.IntegerField(blank=True, help_text='착용 필요 INT', null=True),
        ),
        migrations.AddField(
            model_name='itemdetail',
            name='required_luk',
            field=models.IntegerField(blank=True, help_text='착용 필요 LUK', null=True),
        ),
        migrations.AddField(
            model_name='itemdetail',
            name='required_str',
            field=models.IntegerField(blank=True, help_text='착용 필요 STR', null=True),
        ),
        migrations.AddField(
            model_name='itemdetail',
            name='scissor_count',
            field=models.IntegerField(blank=True, help_text='가위 사용 가능 횟수', null=True),
        ),
        migrations.AddField(
            model_name='itemdetail',
            name='star_force',
            field=models.IntegerField(blank=True, help_text='현재 스타포스 강화 수치', null=True),
        ),
        migrations.AddField(
            model_name='itemdetail',
            name='str_breakdown',
            field=models.JSONField(blank=True, help_text='STR 분해값 {total, base, bonus, scroll}', null=True),
        ),
    ]
