# Generated by Django 5.0.7 on 2024-07-15 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocid', models.CharField(max_length=255, unique=True)),
                ('character_name', models.CharField(max_length=255)),
                ('world_name', models.CharField(max_length=255)),
                ('character_class', models.CharField(max_length=255)),
                ('character_level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(max_length=255, unique=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('characters', models.ManyToManyField(related_name='accounts', to='accounts.character')),
            ],
        ),
    ]
