# Generated by Django 5.0.7 on 2024-07-15 16:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_maplestoryapikey'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='characters',
        ),
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='account',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='accounts.account'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='account_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='character',
            name='ocid',
            field=models.CharField(max_length=255),
        ),
    ]
