# Generated by Django 5.0.7 on 2024-07-15 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_account_characters_account_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='character',
            name='ocid',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
