# Generated by Django 5.1.4 on 2025-11-23 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_character_created_at_character_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=255, unique=True)),
                ('task_type', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('STARTED', 'Started'), ('SUCCESS', 'Success'), ('FAILURE', 'Failure'), ('RETRY', 'Retrying')], default='PENDING', max_length=10)),
                ('progress', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('character_basic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crawl_tasks', to='accounts.character')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['task_id'], name='accounts_cr_task_id_a9d67b_idx'), models.Index(fields=['character_basic', '-created_at'], name='accounts_cr_charact_997f46_idx')],
            },
        ),
    ]
