# Generated by Django 5.1.4 on 2025-11-28 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_crawltask'),
        ('characters', '0014_add_meso_to_characterbasichistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawltask',
            name='character_basic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crawl_tasks', to='characters.characterbasic'),
        ),
    ]
