# Generated by Django 5.1.4 on 2025-11-29 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_crawltask_character_basic'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawltask',
            name='error_type',
            field=models.CharField(blank=True, choices=[('CHARACTER_NOT_FOUND', 'Character Not Found'), ('NETWORK_ERROR', 'Network Error'), ('MAINTENANCE', 'Maintenance'), ('UNKNOWN', 'Unknown')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='crawltask',
            name='technical_error',
            field=models.TextField(blank=True, null=True),
        ),
    ]
